"""add_cwe_table_and_relation

Revision ID: 9e4a8ae1a7c9
Revises: 6a23290ea1fc
Create Date: 2025-12-14 20:11:41.643341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4a8ae1a7c9'
down_revision: Union[str, Sequence[str], None] = '6a23290ea1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cwe',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('owasp_mapping', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vulnerabilities', sa.Column('cwe_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'vulnerabilities', 'cwe', ['cwe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vulnerabilities', type_='foreignkey')
    op.drop_column('vulnerabilities', 'cwe_id')
    op.drop_table('cwe')
    # ### end Alembic commands ###
